[package]
name = "yew-pack-example"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { git = "https://github.com/yewstack/yew.git" }
wasm-logger = "0.2.0"
log = "0.4.11"
wasm-bindgen = "0.2.68"

[build-dependencies]
yew-pack = { path = "../yew-pack" }

[lib]
crate-type = ["cdylib", "rlib"]


[package.metadata.yew-pack]
