[package]
name = "yew_pack_example"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../../Projects/yew/yew" }
yew-functional = { path = "../../../Projects/yew/yew-functional" }
wasm-logger = "0.2.0"
log = "0.4.11"
wasm-bindgen = "0.2.69"

# [lib]
# crate-type = ["cdylib", "rlib"]


[package.metadata.yew-pack]
