[package]
name = "YewStarter"
version = "0.1.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
yew = { git="https://github.com/yewstack/yew" }
yewtil = {git="https://github.com/yewstack/yew", features=["all"]}

[lib]
crate-type = ["cdylib"]
