[package]
name = "recoil-examples"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# yew = { git = "https://github.com/yewstack/yew.git" }
# yew-functional = { git = "https://github.com/yewstack/yew.git" }

anyhow = "1"
yew = { path = "../../../Projects/yew/yew" }
yew-functional = { path = "../../../Projects/yew/yew-functional" }
recoil-yew = { path = "../recoil-yew" }
wasm-bindgen-futures = "0.4"

wasm-logger = "0.2.0"
log = "0.4"
closure = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.4.1"
lazy_static = "1.4.0"

uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
anymap = "0.12.1"


wasm-bindgen-test = "0.3.17"
wasm-bindgen = { version = "0.2.67", features = ["serde-serialize"] }

[lib]
crate-type = ["cdylib", "rlib"]
