[package]
name = "recoil-examples"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../../Projects/yew/yew" }
yew-functional = { path = "../../../Projects/yew/yew-functional" }
recoil-yew = { path = "../recoil-yew" }
wasm-logger = "0.2.0"
log = "0.4"
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen-test = "0.3.17"
wasm-bindgen = { version = "0.2.67", features = ["serde-serialize"] }

[lib]
crate-type = ["cdylib", "rlib"]
