[package]
name = "yew-desktop"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.6.3"
yew = { git = "https://github.com/yewstack/yew.git" }
yew-functional = { git = "https://github.com/yewstack/yew.git" }
