[package]
name = "yew-pack"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.15"
thiserror = "1.0.22"
log = "0.4.11"
env_logger = "0.8.2"
rouille = "3.0.0"
wasm-bindgen-cli-support = "0.2.68"
anyhow = "1.0.34"
json = "0.12.4"
argh = "0.1.4"
