[package]
authors = ["You <you@example.com>"]
categories = ["wasm"]
description = "My awesome Yew app."
edition = "2018"
license = "Apache-2.0/MIT"
name = "yew-app"
readme = "./README.md"
repository = "https://github.com/jetli/create-yew-app.git"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
yew =  { git = "https://github.com/yewstack/yew"}
yew-router = { git = "https://github.com/yewstack/yew",features = ["web_sys"]}
wasm-logger = "0.2.0"
wee_alloc = "0.4.5"
yew-functional = { git = "https://github.com/yewstack/yew"}
wasm-bindgen = { version = "0.2.61", features = ["serde-serialize"]  }
wasm-bindgen-futures = "0.4.3"
futures = "0.3.5"
js-sys = "0.3.40"
serde = { version = "1.0.80", features = ["derive"] }
serde_derive = "^1.0.59"
urlparse = "0.7.3"
fc-macros = {git="https://github.com/jkelleyrtp/yew-fc-macros"}


[dependencies.chrono]
version = "0.4"
features = ["serde", "wasmbind"]

[dependencies.web-sys]
version = "0.3.35"
features = [
  "Document",
  "Element",
  "HtmlCollection",
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.9"

